module.exports = {
  up: queryInterface => queryInterface.bulkInsert('Courses', [
    {
      id: '3dd4b34a-7554-495e-c688-36afda987837',
      title: 'Git and Github',
      description: 'Learn, Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque necessitatibus distinctio adipisci eius, unde dignissimos maxime doloribus quisquam non harum?',
      overview: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nulla id, praesentium odit aspernatur assumenda ducimus architecto pariatur neque sapiente illo ipsum! Earum facere rerum porro fugiat ab perspiciatis autem? Qui fugit optio totam ad itaque eos quam reprehenderit vero, delectus incidunt suscipit eveniet repellat, corporis ratione aperiam temporibus voluptates labore accusamus, aut enim. Maiores, a amet vel error eum eos, inventore dolor laborum sequi quisquam, deleniti alias laboriosam. Officiis, temporibus. Rem, unde placeat perspiciatis vero odit possimus quia labore nesciunt quas. Est, incidunt nihil modi eaque quisquam, natus iste excepturi quos sit nostrum asperiores debitis, repellat laboriosam quibusdam id totam.',
      about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi tenetur amet libero odit dicta quasi facere, sed soluta sapiente cum at voluptate possimus quae accusantium dolorum ea sit quos repellendus maiores dolorem praesentium! Ipsam ut optio voluptatum. Nulla assumenda inventore recusandae doloribus dicta, aliquam eaque vero sunt tempora perferendis animi?',
      categoryId: '3dd3b34a-7554-425e-c688-36afda199619',
      userId: 'ffe25dbe-29ea-4759-8461-ed116f6739dd',
      videoUrl: 'https://player.vimeo.com/video/97243285?title=0&amp;byline=0&amp;portrait=0',
      imgUrl: '',
      duration: '6 months',
      status: 'free',
      amount: 0,
      startDate: '2020-01-15',
      endDate: '2020-07-15',
    },
    {
      id: '3dd3b34a-7554-425e-a688-36afda199615',
      title: 'Unit Testing Tools',
      description: 'Learn mocha and jest, Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque necessitatibus distinctio adipisci eius, unde dignissimos maxime doloribus quisquam non harum?',
      overview: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nulla id, praesentium odit aspernatur assumenda ducimus architecto pariatur neque sapiente illo ipsum! Earum facere rerum porro fugiat ab perspiciatis autem? Qui fugit optio totam ad itaque eos quam reprehenderit vero, delectus incidunt suscipit eveniet repellat, corporis ratione aperiam temporibus voluptates labore accusamus, aut enim. Maiores, a amet vel error eum eos, inventore dolor laborum sequi quisquam, deleniti alias laboriosam. Officiis, temporibus. Rem, unde placeat perspiciatis vero odit possimus quia labore nesciunt quas. Est, incidunt nihil modi eaque quisquam, natus iste excepturi quos sit nostrum asperiores debitis, repellat laboriosam quibusdam id totam.',
      about: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi tenetur amet libero odit dicta quasi facere, sed soluta sapiente cum at voluptate possimus quae accusantium dolorum ea sit quos repellendus maiores dolorem praesentium! Ipsam ut optio voluptatum. Nulla assumenda inventore recusandae doloribus dicta, aliquam eaque vero sunt tempora perferendis animi?',
      categoryId: '3dd3b34a-7554-425e-c688-36afda199619',
      userId: 'ffe25dbe-29ea-4759-8461-ed116f6739dd',
      videoUrl: 'https://player.vimeo.com/video/97243285?title=0&amp;byline=0&amp;portrait=0',
      imgUrl: '',
      duration: '6 months',
      status: 'free',
      amount: 0,
      startDate: '2020-01-15',
      endDate: '2020-07-15',
    },
  ]),
  down: queryInterface => queryInterface.bulkDelete('Courses', null, {})
};
